### ISSUE TITLE
Grant same privileges on multiple schemas

### ISSUE THREAD

**Issue by Olaktal** [brainly/terraform-provider-redshift#108]
Hello

We need to give rights ("select" or more) on multiple schemas.
For now it looks like a lot like
```
resource "redshift_grant" "readonly_schema1" {
  group       = redshift_group.readonlygroup.name
  schema      = "schema1"
  object_type = "table"
  privileges  = ["select"]
}

resource "redshift_grant" "readonly_schema2" {
  group       = redshift_group.readonlygroup.name
  schema      = "schema2"
  object_type = "table"
  privileges  = ["select"]
}
```

It a real mess between since we need A LOT of `redshift_grant` due to our huge amount of groups x schema.
Would it be possible to declare a list of schema instead of a single schema ?
It would look like as follow.

```
resource "redshift_grant" "readonly" {
  group       = redshift_group.readonlygroup.name
  schemas      = ["schema1", "schema2"]
  object_type = "table"
  privileges  = ["select"]
}
```

Don't you have yourself the same problem ?

Vincent

**Comment by winglot** [comment]
I don't see this being an issue as this is what `for_each` loops are for, eg:
```
resource "redshift_grant" "readonly" {
  for_each = toset(["schema1", "schema2"])

  group       = redshift_group.readonlygroup.name
  schema      = each.key
  object_type = "table"
  privileges  = ["select"]
}
```

**Comment by mtesch-um** [comment]
We noticed the same thing -- one thing that helped us was to use the `-parallelism=40` flag for terraform to speed things up a bit. ut of course

**Comment by Olaktal** [comment]
You are right @winglot, it works 👌
