### ISSUE TITLE
Terraform Redshift provider for Redshift in private VPC

### ISSUE THREAD

**Issue by gdhillon** [brainly/terraform-provider-redshift#118]
provider "redshift" {
  host     = var.redshift_host
  username = var.redshift_user
  password = var.redshift_password
}

The above logic works only when the redshift host/endpoint is publicly reachable, which will never (mostly) be the case in prod deployments.
When the TF cloud is trying to make a call, it is not able to reach the Redshift host it is a private VPC. How we are planning to address this?

Thanks
gurmukh

**Comment by winglot** [comment]
Hello,
this is not strictly a provider problem but rather your architecture design issue. You will face the same problem provisioning other resources (eg. RDS databases) that are VPC-only.

The provider itself supports `ALL_PROXY` and `NO_PROXY` environment variables, allowing the use of a SOCKS5 proxy to connect to the Redshift instance.
