### ISSUE TITLE
Configuring a socks proxy via the provider

### ISSUE THREAD

**Issue by henryserrano-contrast** [brainly/terraform-provider-redshift#119]
Any plans on adding support for configuring a socks proxy via the provider similar to this MySQL provider?
https://registry.terraform.io/providers/petoju/mysql/latest/docs#proxy
That way you can use the proxy just for this provider and not others in the same TF project.

**Comment by winglot** [comment]
Hi,
it does support SOCKS5 proxy in a similar way to MySQL provider.

See the relevant documentation: https://registry.terraform.io/providers/brainly/redshift/latest/docs#proxy-support

**Comment by henryserrano-contrast** [comment]
> Hi, it does support SOCKS5 proxy in a similar way to MySQL provider.
> 
> See the relevant documentation: https://registry.terraform.io/providers/brainly/redshift/latest/docs#proxy-support

Thanks for the reply @winglot .

Is the only way to configure the proxy is with an environment variable? Anyway to configure the provider with a proxy argument, something like this?

```
provider "redshift" {
  host          = var.redshift_host
  username = var.redshift_user
  password = var.redshift_password
  proxy        = "socks5://your.proxy:port"
}
```
