### ISSUE TITLE
Issue with revoking privileges while droping user

### ISSUE THREAD

**Issue by vitoravancini** [brainly/terraform-provider-redshift#35]
Hello, 

it seems that when deleting an user there is a query revoking privileges using cascade, which redshift seems to don't accept.
this is the query:

https://github.com/brainly/terraform-provider-redshift/blob/53c926c84456ee555685a5773fe61f5f0eb66807/redshift/resource_redshift_user.go#L393

which retries until terraform exits successfully without actually droping the users.

removing cascade worked for me. 
Id be happy to submit a pull request if thats ok with you.

**Comment by winglot** [comment]
Fixed with #47 and released in `v0.5.2`
