### ISSUE TITLE
"grant ALL on table.." grants more permissions than available in redshift_grant

### ISSUE THREAD

**Issue by mtesch-um** [brainly/terraform-provider-redshift#62]
`GRANT ALL ON TABLE xyz` leaves the table with a permission string of `=arwdRxtD/` whereas the currently allowed set of GRANT permissions ("SELECT", "UPDATE", "INSERT", "DELETE", "DROP", "REFERENCES") can only set the table permission string to `=arwdxD/`.  

Maybe possible solutions are to add an `ALL` possibility, or to add the `R` and `t` permissions?

The RULE and TRIGGER permissions are undocumented, but they are needed for redshift's materialized views implementation.  A user who does not have those permissions to a materialized view can not refresh the view.  https://docs.aws.amazon.com/redshift/latest/dg/materialized-view-refresh-sql-command.html

**Comment by mtesch-um** [comment]
Reference: https://github.com/awslabs/amazon-redshift-utils/blob/master/src/AdminViews/v_generate_user_grant_revoke_ddl.sql explicitly associates `ALL` with `arwdRxtD`, and 'R' with 'RULE' and 't' with 'TRIGGER'

**Comment by winglot** [comment]
The issue has been resolved in #63.
