### ISSUE TITLE
Conflicts with syslog_access and superuser=false

### ISSUE THREAD

**Issue by Imploxion** [brainly/terraform-provider-redshift#95]
Hello.
I am trying to give an user syslog_access="UNRESTRICTED" while this user is not a superuser, since I know this is not a problem in Redshift but I am finding this error o the plan phase.

```
│ Error: Conflicting configuration arguments
│
│   with module....
│   on modules/.../main.tf line 4, in resource "redshift_user" "this":
│    4:   superuser       = var.superuser
│
│ "superuser": conflicts with syslog_access
```

There is a way to solve it? Thanks

**Comment by winglot** [comment]
Hello,
the conflict is due to how terraform handles conflicting fields, without taking the value into consideration. I will create a necessary change to allow use of `syslog_access ` and `superuser` and only do the validation when the later is set to `true`.
